exp_name: ???
exp_type: ???
run_name: null
base_dir: .

jobid: null
seed: null
debug: false
use_float64: false

warm_start_idx: null
save: true
use_mlflow: true
save_source: true
ema: false

train: true
evaluate: true
evaluation:
 batchsize: 1024

sample: true
plotting:
 loss: true

mlflow:
 db: '${base_dir}/runs/${exp_name}/mlflow/mlflow.db'
 artifacts: '${base_dir}/runs/${exp_name}/mlflow/artifacts'

defaults:
 - _self_
 - hydra
