#!/usr/bin/env python3
"""Hybrid conservative core and dense residual model for CaloChallenge showers.

The most energetic cells are generated by the sequential birth process.  A
conditional Dirichlet decoder then distributes the remaining energy over all
official detector cells.  Layer-energy budgets are exact by construction.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
import random
from typing import Sequence

import numpy as np
import torch
from torch import Tensor, nn
import torch.nn.functional as F

import gpu_model as gm


@dataclass(frozen=True)
class ShapeModelConfig:
    voxel_count: int = 368
    layer_count: int = 5
    condition_dim: int = 6
    core_components: int = 48
    hidden_dim: int = 480
    transformer_layers: int = 6
    attention_heads: int = 6
    mixture_components: int = 16
    residual_hidden_dim: int = 1536
    residual_layers: int = 4
    minimum_concentration: float = 1e-2
    maximum_concentration: float = 100.0
    target_smoothing: float = 1e-6

    def __post_init__(self) -> None:
        integers = (
            self.voxel_count,
            self.layer_count,
            self.condition_dim,
            self.core_components,
            self.hidden_dim,
            self.transformer_layers,
            self.attention_heads,
            self.mixture_components,
            self.residual_hidden_dim,
            self.residual_layers,
        )
        if min(integers) < 1:
            raise ValueError("all shape-model dimensions must be positive")
        if self.hidden_dim % self.attention_heads:
            raise ValueError("hidden_dim must be divisible by attention_heads")
        if self.core_components > self.voxel_count:
            raise ValueError("core_components cannot exceed voxel_count")
        if not 0.0 < self.minimum_concentration < self.maximum_concentration:
            raise ValueError("invalid concentration limits")
        if self.target_smoothing <= 0.0:
            raise ValueError("target_smoothing must be positive")

    def to_dict(self) -> dict:
        return asdict(self)


def dense_to_core_states(
    showers_mev: np.ndarray | Tensor,
    voxel_features: np.ndarray | Tensor,
    core_components: int,
) -> tuple[list[gm.WeightedSetState], Tensor]:
    """Convert dense showers to unit-mass top-k states and dense fractions."""
    showers = torch.as_tensor(showers_mev, dtype=torch.float32, device="cpu")
    features = torch.as_tensor(voxel_features, dtype=torch.float32, device="cpu")
    if showers.ndim != 2 or features.ndim != 2 or showers.shape[1] != len(features):
        raise ValueError("showers and voxel_features have incompatible shapes")
    if not 0 < core_components <= showers.shape[1]:
        raise ValueError("invalid core component count")
    showers = torch.nan_to_num(showers, nan=0.0, posinf=0.0, neginf=0.0).clamp_min(0.0)
    totals = showers.sum(dim=-1)
    fractions = showers / totals[:, None].clamp_min(1e-12)
    states: list[gm.WeightedSetState] = []
    for row, total in zip(fractions, totals):
        if float(total) <= 0.0:
            states.append(gm.empty_state(1.0, features.shape[1], device="cpu", dtype=torch.float32))
            continue
        values, indices = torch.topk(row, core_components, sorted=True)
        positive = values > 0.0
        values = values[positive]
        indices = indices[positive]
        represented = float(values.double().sum())
        states.append(
            gm.WeightedSetState(
                values,
                features[indices],
                max(0.0, 1.0 - represented),
                1.0,
                tuple(int(value) for value in indices.tolist()),
            )
        )
    return states, fractions


class HybridVoxelShapeModel(nn.Module):
    """Sequential categorical core plus full-geometry stochastic residual."""

    def __init__(
        self,
        config: ShapeModelConfig,
        voxel_features: np.ndarray | Tensor,
        layer_indices: np.ndarray | Tensor,
    ):
        super().__init__()
        self.config = config
        features = torch.as_tensor(voxel_features, dtype=torch.float32)
        layers = torch.as_tensor(layer_indices, dtype=torch.long)
        if features.shape != (config.voxel_count, 3):
            raise ValueError("voxel_features must have shape [voxel_count, 3]")
        if layers.shape != (config.voxel_count,):
            raise ValueError("layer_indices must have shape [voxel_count]")
        if int(layers.min()) < 0 or int(layers.max()) >= config.layer_count:
            raise ValueError("layer indices are outside the configured range")
        neural = gm.NeuralConfig(
            feature_dim=3,
            max_components=config.core_components,
            hidden_dim=config.hidden_dim,
            embedding_dim=config.hidden_dim,
            transformer_layers=config.transformer_layers,
            attention_heads=config.attention_heads,
            mixture_components=config.mixture_components,
            condition_dim=config.condition_dim,
        )
        self.core = gm.VoxelBirthOnlyModel(neural, features)
        self.register_buffer("layer_indices", layers)
        geometry_width = 3 + config.layer_count
        self.cell_encoder = gm.MLP(
            geometry_width, config.hidden_dim, config.hidden_dim, layers=3
        )
        self.residual_head = gm.MLP(
            2 * config.hidden_dim + 2,
            config.residual_hidden_dim,
            1,
            layers=config.residual_layers,
        )

    @property
    def device(self) -> torch.device:
        return next(self.parameters()).device

    @property
    def dtype(self) -> torch.dtype:
        return next(self.parameters()).dtype

    def _core_grids(self, states: Sequence[gm.WeightedSetState]) -> tuple[Tensor, Tensor]:
        masses = torch.zeros(
            (len(states), self.config.voxel_count), device=self.device, dtype=self.dtype
        )
        occupied = torch.zeros(
            (len(states), self.config.voxel_count), device=self.device, dtype=torch.bool
        )
        counts = [state.n for state in states]
        if not sum(counts):
            return masses, occupied
        index_parts = []
        mass_parts = []
        for state in states:
            if not state.n:
                continue
            if state.lineages and all(0 <= value < self.config.voxel_count for value in state.lineages):
                indices = torch.tensor(state.lineages, dtype=torch.long)
            else:
                indices = self.core._cell_indices(state.features).cpu()
            index_parts.append(indices)
            mass_parts.append(state.masses)
        rows = torch.repeat_interleave(
            torch.arange(len(states), device=self.device),
            torch.tensor(counts, device=self.device),
        )
        indices = torch.cat(index_parts).to(device=self.device)
        values = torch.cat(mass_parts).to(device=self.device, dtype=self.dtype)
        masses[rows, indices] = values
        occupied[rows, indices] = True
        return masses, occupied

    def residual_parameters(
        self,
        states: Sequence[gm.WeightedSetState],
        conditions: Tensor,
    ) -> tuple[Tensor, Tensor, Tensor]:
        """Return per-cell Dirichlet concentrations and core occupancy grids."""
        if len(states) != len(conditions):
            raise ValueError("one condition is required per core state")
        count = len(states)
        conditions = conditions.to(device=self.device, dtype=self.dtype)
        encoded = self.core.encode(
            states,
            torch.full((count,), self.core.config.horizon, device=self.device, dtype=self.dtype),
            torch.tensor([state.n for state in states], device=self.device),
            conditions,
        )
        features = self.core.voxel_features.to(device=self.device, dtype=self.dtype)
        one_hot_layers = F.one_hot(
            self.layer_indices, num_classes=self.config.layer_count
        ).to(device=self.device, dtype=self.dtype)
        cell_context = self.cell_encoder(torch.cat((features, one_hot_layers), dim=-1))
        core_masses, occupied = self._core_grids(states)
        decoder_input = torch.cat(
            (
                encoded.pooled[:, None, :].expand(-1, self.config.voxel_count, -1),
                cell_context[None, :, :].expand(count, -1, -1),
                core_masses[:, :, None],
                occupied.to(self.dtype)[:, :, None],
            ),
            dim=-1,
        )
        raw = self.residual_head(decoder_input).squeeze(-1)
        concentration = F.softplus(raw) + self.config.minimum_concentration
        concentration = concentration.clamp(max=self.config.maximum_concentration)
        return concentration, core_masses, occupied

    def sampled_core_nll(
        self,
        states: Sequence[gm.WeightedSetState],
        conditions: Tensor,
        corruption: gm.CorruptionConfig,
        generator: torch.Generator,
    ) -> dict[str, Tensor]:
        """Unbiased one-birth-per-shower estimate of the core path objective.

        Official training uses zero deterministic flow.  This makes a partial
        reverse state exactly a random prefix of a random birth permutation,
        avoiding materializing all 48 path states per shower.
        """
        if corruption.gamma != 0.0 or corruption.split_rate != 0.0:
            raise ValueError("sampled core objective requires deletion-only zero-flow corruption")
        conditions = conditions.to(device=self.device, dtype=self.dtype)
        counts = torch.tensor([state.n for state in states], device=self.device, dtype=torch.long)
        totals = torch.ones(len(states), device=self.device, dtype=self.dtype)
        count_nll = F.cross_entropy(
            self.core.leaf_logits(totals, conditions), counts, reduction="mean"
        )
        partial_states: list[gm.WeightedSetState] = []
        times: list[float] = []
        budgets: list[int] = []
        target_masses: list[Tensor] = []
        target_features: list[Tensor] = []
        condition_rows: list[Tensor] = []
        for row, state in enumerate(states):
            if state.n == 0:
                continue
            order = torch.randperm(state.n, generator=generator)
            birth_times = torch.sort(
                torch.rand(state.n, generator=generator) * corruption.nucleation_duration
            ).values
            rank = int(torch.randint(state.n, (1,), generator=generator))
            prior = order[:rank]
            target = int(order[rank])
            prior_masses = state.masses[prior]
            prior_features = state.features[prior]
            # Compute the reverse-state reservoir from the masses that have
            # not yet been born plus the endpoint residual.  Subtracting the
            # represented prefix from 1.0 can round to exactly zero for rare
            # <=48-cell showers even while a tiny positive target remains,
            # making the continuous birth density non-finite.
            unborn = order[rank:]
            reservoir = float(state.reservoir) + float(state.masses[unborn].double().sum())
            prior_lineages = tuple(state.lineages[int(index)] for index in prior.tolist())
            partial_states.append(
                gm.WeightedSetState(
                    prior_masses,
                    prior_features,
                    reservoir,
                    1.0,
                    prior_lineages,
                )
            )
            times.append(float(birth_times[rank]))
            budgets.append(state.n)
            target_masses.append(state.masses[target])
            target_features.append(state.features[target])
            condition_rows.append(conditions[row])
        if not partial_states:
            zero = count_nll * 0.0
            return {"loss": count_nll, "count_nll": count_nll, "birth_nll": zero}
        log_prob = self.core.birth_log_prob(
            partial_states,
            torch.tensor(times, device=self.device, dtype=self.dtype),
            torch.tensor(budgets, device=self.device),
            torch.stack(target_masses),
            torch.stack(target_features),
            torch.stack(condition_rows),
        )
        birth_nll = -log_prob.mean()
        return {
            "loss": count_nll + birth_nll,
            "count_nll": count_nll,
            "birth_nll": birth_nll,
        }

    def residual_nll(
        self,
        states: Sequence[gm.WeightedSetState],
        conditions: Tensor,
        dense_fractions: Tensor,
    ) -> dict[str, Tensor]:
        """Dirichlet likelihood for non-core energy, evaluated layer by layer."""
        concentration, core_masses, occupied = self.residual_parameters(states, conditions)
        targets = dense_fractions.to(device=self.device, dtype=self.dtype) - core_masses
        targets = targets.clamp_min(0.0)
        # Evaluate every (shower, layer) Dirichlet in one tensor program.  The
        # former nested Python loop performed up to 320 device synchronizations
        # per optimizer step and left the GPU waiting on the host.
        layer_cells = F.one_hot(
            self.layer_indices, num_classes=self.config.layer_count
        ).T.to(torch.bool)
        eligible = layer_cells[None, :, :] & ~occupied[:, None, :]
        eligible_values = eligible.to(self.dtype)
        counts = eligible_values.sum(dim=-1)
        residual_by_layer = targets[:, None, :] * eligible_values
        totals = residual_by_layer.sum(dim=-1)
        valid = (counts >= 2.0) & (totals > 1e-12)
        denominator = (
            totals[:, :, None] + self.config.target_smoothing * counts[:, :, None]
        ).clamp_min(self.config.target_smoothing)
        smoothed = (
            (targets[:, None, :] + self.config.target_smoothing)
            * eligible_values
            / denominator
        )
        safe_smoothed = torch.where(eligible, smoothed, torch.ones_like(smoothed))
        alpha = concentration[:, None, :]
        alpha_sum = (alpha * eligible_values).sum(dim=-1).clamp_min(
            self.config.minimum_concentration
        )
        log_probability = (
            torch.lgamma(alpha_sum)
            - (torch.lgamma(alpha) * eligible_values).sum(dim=-1)
            + (((alpha - 1.0) * safe_smoothed.log()) * eligible_values).sum(dim=-1)
        )
        terms = torch.where(
            valid,
            -log_probability / counts.clamp_min(1.0),
            torch.zeros_like(log_probability),
        )
        expected = alpha / alpha_sum[:, :, None]
        cross_entropies = -(
            smoothed * expected.clamp_min(1e-12).log() * eligible_values
        ).sum(dim=-1)
        valid_values = valid.to(self.dtype)
        normalizer = valid_values.sum().clamp_min(1.0)
        residual_nll = (terms * valid_values).sum() / normalizer
        residual_cross_entropy = (cross_entropies * valid_values).sum() / normalizer
        return {
            "loss": residual_nll,
            "residual_nll": residual_nll,
            "residual_cross_entropy": residual_cross_entropy,
        }

    @torch.no_grad()
    def project_core_to_layers(
        self,
        states: Sequence[gm.WeightedSetState],
        layer_fractions: Tensor,
    ) -> list[gm.WeightedSetState]:
        """Project generated core masses so no layer exceeds its energy budget."""
        budgets = layer_fractions.to(device=self.device, dtype=self.dtype)
        projected: list[gm.WeightedSetState] = []
        for row, state in enumerate(states):
            if not state.n:
                projected.append(state)
                continue
            indices = self.core._cell_indices(state.features)
            layers = self.layer_indices[indices]
            masses = state.masses.to(device=self.device, dtype=self.dtype).clone()
            keep = torch.ones(state.n, device=self.device, dtype=torch.bool)
            for layer in range(self.config.layer_count):
                selected = layers == layer
                current = masses[selected].sum()
                target = budgets[row, layer].clamp_min(0.0)
                if float(target) <= 0.0:
                    keep &= ~selected
                elif float(current) > float(target):
                    masses[selected] *= target / current
            masses = masses[keep]
            indices = indices[keep]
            represented = float(masses.double().sum().cpu())
            projected.append(
                gm.WeightedSetState(
                    masses,
                    self.core.voxel_features[indices].to(device=self.device, dtype=self.dtype),
                    max(0.0, 1.0 - represented),
                    1.0,
                    tuple(int(value) for value in indices.cpu().tolist()),
                )
            )
        return projected

    @torch.no_grad()
    def sample_fractions(
        self,
        conditions: Tensor,
        layer_fractions: Tensor,
        corruption: gm.CorruptionConfig,
        rng: random.Random,
    ) -> tuple[Tensor, list[gm.WeightedSetState]]:
        """Generate dense unit-normalized showers with exact layer fractions."""
        conditions = conditions.to(device=self.device, dtype=self.dtype)
        layer_fractions = layer_fractions.to(device=self.device, dtype=self.dtype)
        core_states = self.core.sample_batch(
            [1.0] * len(conditions),
            corruption,
            conditions=[row for row in conditions],
            rng=rng,
        )
        states = self.project_core_to_layers(core_states, layer_fractions)
        concentration, core_masses, occupied = self.residual_parameters(states, conditions)
        result = core_masses.clone()
        for row in range(len(states)):
            for layer in range(self.config.layer_count):
                layer_mask = self.layer_indices == layer
                core_total = result[row, layer_mask].sum()
                remaining = (layer_fractions[row, layer] - core_total).clamp_min(0.0)
                eligible = layer_mask & ~occupied[row]
                if float(remaining) <= 0.0 or int(eligible.sum()) == 0:
                    continue
                weights = torch.distributions.Dirichlet(concentration[row, eligible]).sample()
                result[row, eligible] = remaining * weights
        normalizer = result.sum(dim=-1, keepdim=True).clamp_min(1e-12)
        requested = layer_fractions.sum(dim=-1, keepdim=True)
        # Normally both sums are exactly one.  This final correction only
        # protects against floating-point drift in externally supplied budgets.
        result = result * (requested / normalizer)
        return result, states


def contiguous_layer_indices(layer_ids: np.ndarray | Tensor) -> tuple[Tensor, tuple[int, ...]]:
    values = np.asarray(layer_ids, dtype=np.int64).reshape(-1)
    unique = tuple(int(value) for value in np.unique(values))
    mapping = {value: index for index, value in enumerate(unique)}
    return torch.tensor([mapping[int(value)] for value in values], dtype=torch.long), unique
