exp_type: calogan
exp_name: CaloGAN
dtype: float32

model_type: shape
sample_us: false
energy_model: /path/to/trained/energy-model  # used if sample_us==true
n_samples: 100000   # used if sample_us==true

data:
  training_file: /gpfs/home/acad/ucl-cp3/favaro/datasets/calogan_training/train_eplus.hdf5
  test_file: /gpfs/home/acad/ucl-cp3/favaro/datasets/calogan_training/test_eplus.hdf5
  bin_edges: [0, 288, 432, 504]
  return_us: false
  transforms: {
    NormalizeLayerEnergyGAN: {},
    ExclusiveLogitTransformGAN: {delta: 1.0e-6, rescale: False},
    GlobalStandardizeFromFileGAN: {model_dir: None, eps: 1.e-10},
    LogEnergyGAN: {},
    ScaleEnergyGAN: {e_min: 6.907755, e_max: 13.815510},
  }

finetuning: false
load_sample: false
evaluation:
  eval_dataset: "CaloGAN"
  eval_mode: low-level
  eval_hdf5_file: /gpfs/home/acad/ucl-cp3/favaro/datasets/calogan_full_cls/full_cls_eplus.hdf5
  eval_cls_n_layer: 2
  eval_cls_n_hidden: 2048
  eval_cls_dropout: 0.0
  eval_cls_lr: 2.e-4
  eval_cls_batch_size: 1000
  eval_cls_n_epochs: 100
  eval_cls_save_mem: True

defaults:
 - /default
 - /training: cfm/shape
 - /model: cfm_calogan/cfm_eplus